logging.level.root=INFO
logging.level.com.example.address_book=INFO
logging.file.name=logs/address-book-prod.log
logging.pattern.console=
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n